import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Script from 'next/script'
const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <Script src="https://telegram.org/js/telegram-web-app.js"></Script>

      <body className={inter.className}>
        <div className=" px-4">
          {children}
        </div>

      </body>
    </html>
  );
}
